SELECT MEMBER_ID, MEMBER_NAME, GENDER, LEFT(DATE_OF_BIRTH, 10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 and GENDER = 'W' and TLNO IS NOT NULL
ORDER BY MEMBER_ID

# SELECT MEMBER_ID, MEMBER_NAME, GENDER, LEFT(DATE_OF_BIRTH,10) AS "DATE_OF_BIRTH"
# FROM MEMBER_PROFILE
# WHERE MONTH(DATE_OF_BIRTH) = 3 and TLNO != "NULL" and GENDER = "W"
# ORDER BY MEMBER_ID



# # SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS "DATE_OF_BIRTH"
# # FROM MEMBER_PROFILE
# # WHERE TLNO != 'NULL' and DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03' and GENDER = 'W'
# # ORDER BY MEMBER_ID;


# # # DATE_OF_BIRTH LIKE '%-03-%'
# # # 처음에는 이런식으로 문자를 했지만 mySQL 내에서 3월에 해당하는 부분에 맞게 해줄 수가 있었다.
