SELECT ANIMAL_ID, NAME, LEFT(DATETIME, 10) AS DATE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# SELECT ANIMAL_ID, NAME, LEFT(DATE(DATETIME),10) AS '날짜'
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID

# # SELECT ANIMAL_ID, NAME, LEFT(DATETIME,10) AS '날짜'
# # FROM ANIMAL_INS
# # ORDER BY ANIMAL_ID

# # # SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜
# # # 이게 원래 모범답안
