SELECT TRUNCATE(PRICE, -4) AS PRICE, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY TRUNCATE(PRICE, -4)
ORDER BY PRICE
# 위로 네자리에 관해 버림

# SELECT TRUNCATE(PRICE, -4) AS PRICE_GROUP, COUNT(*) AS PROCUTS
# FROM PRODUCT
# GROUP BY TRUNCATE(PRICE, -4)
# ORDER BY PRICE
