SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE "강원도%"
ORDER BY FACTORY_ID

# SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
# FROM FOOD_FACTORY
# WHERE ADDRESS LIKE "강원도%"
# ORDER BY FACTORY_ID

# # -- 코드를 입력하세요
# # SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
# # FROM FOOD_FACTORY
# # WHERE ADDRESS LIKE '%강원도%'
# # ORDER BY FACTORY_ID
# # -- 앞 뒤로 %를 붙여주면 그 단어가 포함된 것을 찾는다.
