SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N')
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE "경기도%"
ORDER BY WAREHOUSE_ID

# SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N')
# FROM FOOD_WAREHOUSE
# WHERE ADDRESS LIKE "경기도%"
# ORDER BY WAREHOUSE_ID


# # # SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
# # # CASE WHEN FREEZER_YN is NULL THEN 'N' ELSE FREEZER_YN END AS FREEZER_YN
# # # FROM FOOD_WAREHOUSE
# # # WHERE ADDRESS like '경기도%'
# # # ORDER BY WAREHOUSE_ID

# # -- 위 아래 둘다 가능 근데 밑에가 훨씬 나은듯

# # SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
# # ifnull(FREEZER_YN,'N')
# # from FOOD_WAREHOUSE
# # where ADDRESS like '%경기도%'
# # ORDER BY WAREHOUSE_ID
