SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC

# SELECT ANIMAL_ID, NAME, DATETIME
# FROM ANIMAL_INS
# ORDER BY NAME, DATETIME DESC

# # -- 코드를 입력하세요
# # SELECT ANIMAL_ID, NAME, DATETIME
# # FROM ANIMAL_INS
# # ORDER BY NAME ASC, DATETIME DESC
# # -- 처음엔 NAME에 대해서 이름순으로 조회하고, 이름이 같은 경우에 대해서는 DATETIME을 거꾸로 생각하므로
