SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC

# SELECT NAME, DATETIME
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID DESC

# # -- 코드를 입력하세요
# # SELECT NAME, DATETIME
# # FROM ANIMAL_INS
# # ORDER BY ANIMAL_ID DESC
