SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(A.DATETIME, B.DATETIME)
# A에서 B를 빼므로 길수록 수가 작으니 오름차순으로 해도 된다.
LIMIT 2

# SELECT B.ANIMAL_ID, B.NAME
# FROM ANIMAL_INS A
# JOIN ANIMAL_OUTS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# ORDER BY DATEDIFF(B.DATETIME, A.DATETIME) DESC
# LIMIT 2
# -- B에서 A를 빼므로 클 수록 차이가 크므로 내림차순이 맞다. (순서가 달라서))

# # SELECT A.ANIMAL_ID, A.NAME
# # FROM ANIMAL_INS A, ANIMAL_OUTS B
# # WHERE A.ANIMAL_ID = B.ANIMAL_ID
# # ORDER BY DATEDIFF(A.DATETIME, B.DATETIME)
# # LIMIT 2

# # -- ANIMAL_OUTS의 ANIMAL_ID와 ANIMAL_INS의 ANIMAL_ID의 외래 키이다.
# # -- DATE가 있을 경우 차이는 DATEDIFF로 한다.

# # -- FROM ANIMAL_INS를 A로 하고 ANIMAL_OUTS를 B로 해서 SELECT에서 A.를 통하여 나타내어준다.
