SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE (NAME LIKE '%el%' or NAME LIKE 'el%' or NAME LIKE '%el') and ANIMAL_TYPE = 'Dog'
ORDER BY NAME

# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_INS
# WHERE (NAME LIKE 'EL%' or NAME LIKE '%EL' or NAME LIKE '%EL%') and ANIMAL_TYPE = 'Dog'
# ORDER BY NAME

# # SELECT ANIMAL_ID, NAME
# # FROM ANIMAL_INS
# # WHERE NAME LIKE '%EL%' AND ANIMAL_TYPE = 'Dog'
# # ORDER BY NAME
