SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID

# SELECT ANIMAL_ID
# FROM ANIMAL_INS
# WHERE NAME IS NOT NULL

# # SELECT ANIMAL_ID
# # FROM ANIMAL_INS
# # WHERE NAME IS NOT NULL
