SELECT ORDER_ID, PRODUCT_ID, LEFT(OUT_DATE, 10),
# IF(OUT_DATE <= '2022-05-01', '출고완료',IF(OUT_DATE IS NULL, '출고미정','출고대기')) as 출고여부
CASE WHEN OUT_DATE <= '2022-05-01' THEN "출고완료"
WHEN OUT_DATE IS NULL THEN "출고미정" # CASE WHEN ~~ THEN ~~ WHEN ~~ THEN ~~ ELSE ~~
ELSE "출고대기" END AS "출고여부"
FROM FOOD_ORDER
ORDER BY ORDER_ID

# SELECT ORDER_ID, PRODUCT_ID, LEFT(OUT_DATE, 10),
# IF(OUT_DATE <= '2022-05-01', '출고완료',IF(OUT_DATE IS NULL, '출고미정','출고대기')) as 출고여부
# FROM FOOD_ORDER
# ORDER BY ORDER_ID
