SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
# FOOD_TYPE으로 그룹해준 곳에서 MAX(FAVORITES)를 구하는데 여기 안에 만약 만족하는
# (FOOD_TYPE, FAVORITES)가 있다면 그것을 출력한다.
ORDER BY FOOD_TYPE DESC

# SELECT FOOD_TYPE,  REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE, FAVORITES) IN
# (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO
# GROUP BY FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC

# # FOOD_TYPE와 FAVORITES는 따로 ()로 뽑아서 그 안에서 FOOD_TYPE, MAX(FAVORITES)에 관하여 REST_INFO 테이블에서 조사하고 FOOD_TYPE에 대해 조사해서 그것 중에 있는 것만 IN으로 뽑아준다.


