
SELECT A.PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
FROM PRODUCT A LEFT JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC













# SELECT A.PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
# FROM PRODUCT A
# JOIN OFFLINE_SALE B
# ON A.PRODUCT_ID = B.PRODUCT_ID
# GROUP BY A.PRODUCT_CODE
# ORDER BY SUM(A.PRICE * B.SALES_AMOUNT) DESC, A.PRODUCT_CODE

# # 둘이 조금 다른 거 같은데 맞다.. 똑같긴 한듯
# # SELECT A.PRODUCT_CODE, A.PRICE * SUM(B.SALES_AMOUNT) AS SALES
# # FROM PRODUCT A
# # JOIN OFFLINE_SALE B
# # ON A.PRODUCT_ID = B.PRODUCT_ID
# # GROUP BY A.PRODUCT_CODE
# # ORDER BY SALES DESC, PRODUCT_CODE ASC