# SELECT COUNT(*) AS USERS
# FROM USER_INFO
# WHERE AGE >= 20 and AGE <= 29 and YEAR(JOINED) = 2021

# # SELECT COUNT(*) AS USERS
# # FROM USER_INFO
# # WHERE YEAR(JOINED) = 2021 and AGE >= 20 and AGE<= 29

SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE JOINED LIKE "2021%" AND AGE >= 20 AND AGE <= 29










