
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE != B.SEX_UPON_OUTCOME
ORDER BY A.ANIMAL_ID






# SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
# FROM ANIMAL_INS A
# JOIN ANIMAL_OUTS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE (A.SEX_UPON_INTAKE NOT LIKE '%Spayed%' and A.SEX_UPON_INTAKE NOT LIKE '%Neutered%') and (B.SEX_UPON_OUTCOME LIKE '%Spayed%' or B.SEX_UPON_OUTCOME LIKE '%Neutered%')
# ORDER BY A.ANIMAL_ID

# # SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME # 여기는 A,B 모두 해도 된다. 같아서
# # FROM ANIMAL_INS A
# #     JOIN ANIMAL_OUTS B
# # ON A.ANIMAL_ID = B.ANIMAL_ID
# # WHERE A.SEX_UPON_INTAKE != B.SEX_UPON_OUTCOME
# # ORDER BY A.ANIMAL_ID



# # SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
# # FROM ANIMAL_INS A
# #     JOIN ANIMAL_OUTS B
# # ON A.ANIMAL_ID = B.ANIMAL_ID
# # WHERE A.SEX_UPON_INTAKE != B.SEX_UPON_OUTCOME
# # ORDER BY A.ANIMAL_ID

# # # 이거는 안되는데 왜 안되는지는 모르겠다.. 위로 그냥 해도 될거 같긴 한데 복잡할때는 밑에가 낫지 않나
# # # WHERE A.SEX_UPON_INTAKE = "Intact%" and (B.SEX_UPON_OUTCOME = "Spayed%" or B.SEX_UPON_OUTCOME = "Neutered%")