-- 코드를 입력하세요
SELECT C.HISTORY_ID,
ROUND(DAILY_FEE * (DATEDIFF(END_DATE,START_DATE) + 1) * (100 - COALESCE(DISCOUNT_RATE,0)) / 100,0) AS FEE
     FROM (
        SELECT B.HISTORY_ID, A.CAR_TYPE, A.DAILY_FEE, B.START_DATE, B.END_DATE, CASE WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN "90일 이상"
     WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN "30일 이상"
     WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN "7일 이상"
     END AS DURATION
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
         LEFT JOIN CAR_RENTAL_COMPANY_CAR A
         ON A.CAR_ID = B.CAR_ID
         WHERE A.CAR_TYPE ='트럭') AS C
         LEFT JOIN (
             SELECT DURATION_TYPE, DISCOUNT_RATE
             FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
             WHERE CAR_TYPE = '트럭') AS D
             ON C.DURATION = D.DURATION_TYPE
    ORDER BY FEE DESC, HISTORY_ID DESC;