
SELECT MAIN.APNT_NO, MAIN.PT_NAME, MAIN.PT_NO, MAIN.MCDP_CD, DOC.DR_NAME, MAIN.APNT_YMD
FROM (
    SELECT AP.APNT_NO, PA.PT_NAME, AP.PT_NO, AP.MCDP_CD, AP.APNT_YMD, AP.MDDR_ID
    FROM PATIENT AS PA
    JOIN (
        SELECT *
        FROM APPOINTMENT
        WHERE LEFT(APNT_YMD, 10) = "2022-04-13" AND APNT_CNCL_YN = "N" AND MCDP_CD = "CS"
    ) AS AP
    ON PA.PT_NO = AP.PT_NO
) AS MAIN
JOIN DOCTOR AS DOC
ON MAIN.MDDR_ID = DOC.DR_ID
ORDER BY APNT_YMD, PT_NO