SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = 'CS'  -- 흉부외과(CS) 진료만 선택
AND A.APNT_CNCL_YN = 'N'  -- 취소되지 않은 예약
AND DATE(A.APNT_YMD) = '2022-04-13'  -- 2022년 4월 13일 예약된 데이터만
ORDER BY A.APNT_YMD ASC;

# SELECT MAIN.APNT_NO, MAIN.PT_NAME, MAIN.PT_NO, MAIN.MCDP_CD, DOC.DR_NAME, MAIN.APNT_YMD
# FROM (
#     SELECT AP.APNT_NO, PA.PT_NAME, AP.PT_NO, AP.MCDP_CD, AP.APNT_YMD, AP.MDDR_ID
#     FROM PATIENT AS PA
#     JOIN (
#         SELECT *
#         FROM APPOINTMENT
#         WHERE LEFT(APNT_YMD, 10) = "2022-04-13" AND APNT_CNCL_YN = "N" AND MCDP_CD = "CS"
#     ) AS AP
#     ON PA.PT_NO = AP.PT_NO
# ) AS MAIN
# JOIN DOCTOR AS DOC
# ON MAIN.MDDR_ID = DOC.DR_ID
# ORDER BY APNT_YMD, PT_NO

# SELECT MAIN.APNT_NO, MAIN.PT_NAME, MAIN.PT_NO, MAIN.MCDP_CD, DOC.DR_NAME, MAIN.APNT_YMD
# FROM (
#     SELECT AP.APNT_NO, PA.PT_NAME, AP.PT_NO, AP.MCDP_CD, AP.APNT_YMD, AP.MDDR_ID
#     FROM PATIENT AS PA
#     JOIN(
#         SELECT *
#         FROM APPOINTMENT
#         WHERE LEFT(APNT_YMD, 10) = "2022-04-13" and APNT_CNCL_YN = "N" and MCDP_CD = "CS"
#     ) AS AP     # APPOINTMENT를 AP로 묶는다.
#     ON PA.PT_NO = AP.PT_NO   # PATIENT와 APPOINTMENT를 PT_NO로 묶는다.
# ) AS MAIN       # PATIENT와 APPOINTMENT를 MAIN으로 JOIN함
# JOIN DOCTOR AS DOC           # DOCTOR를 DOC로 해서 MAIN과 DOCTOR를 JOIN함
# ON MAIN.MDDR_ID = DOC.DR_ID  # DOC와 MAIN을 MDDR_ID와 DR_ID로 묶는다.
# ORDER BY APNT_YMD, PT_NO