# SELECT DR_NAME, DR_ID, MCDP_CD, LEFT(HIRE_YMD,10)
# FROM DOCTOR
# WHERE MCDP_CD = "CS" or MCDP_CD = "GS"
# ORDER BY HIRE_YMD DESC, DR_NAME

SELECT DR_NAME, DR_ID, MCDP_CD, LEFT(HIRE_YMD, 10)
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC









