
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != "Aged"
ORDER BY ANIMAL_ID







# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_INS
# WHERE INTAKE_CONDITION != 'Aged'
# ORDER BY ANIMAL_ID

# # SELECT ANIMAL_ID, NAME
# # FROM ANIMAL_INS
# # WHERE INTAKE_CONDITION != "Aged"

# # # -- 코드를 입력하세요
# # # SELECT ANIMAL_ID, NAME
# # # FROM ANIMAL_INS
# # # WHERE INTAKE_CONDITION != 'Aged'
# # # -- GROUP BY를 안하고 바로 WHERE를 사용가능한가봄