SELECT B.MEMBER_NAME, A.REVIEW_TEXT, LEFT(REVIEW_DATE, 10)
FROM REST_REVIEW A
JOIN 
(
    SELECT R.MEMBER_ID, M.MEMBER_NAME, RANK() OVER(ORDER BY CNT DESC) AS R
    FROM (
        SELECT *, COUNT(MEMBER_ID) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ) AS R
    JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
) B 
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.R = 1
ORDER BY A.REVIEW_DATE


# SELECT B.MEMBER_NAME, A.REVIEW_TEXT, LEFT(A.REVIEW_DATE, 10)
# FROM REST_REVIEW A
# JOIN (
#     SELECT R.MEMBER_ID, M.MEMBER_NAME, RANK() OVER(ORDER BY CNT DESC) AS R
#     FROM (
#         SELECT *, COUNT(MEMBER_ID) AS CNT
#         FROM REST_REVIEW
#         GROUP BY MEMBER_ID) AS R
#         JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID) B
# ON A.MEMBER_ID = B.MEMBER_ID
# WHERE B.R = 1
# ORDER BY A.REVIEW_DATE