
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (
    SELECT MEMBER_ID FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC 
    LIMIT 1
)
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT


# SELECT B.MEMBER_NAME, A.REVIEW_TEXT, LEFT(A.REVIEW_DATE, 10)
# FROM REST_REVIEW A
# JOIN (
#     SELECT R.MEMBER_ID, M.MEMBER_NAME, RANK() OVER(ORDER BY CNT DESC) AS R
#     FROM (
#         SELECT *, COUNT(MEMBER_ID) AS CNT
#         FROM REST_REVIEW
#         GROUP BY MEMBER_ID) AS R
#         JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID) B
# ON A.MEMBER_ID = B.MEMBER_ID
# WHERE B.R = 1
# ORDER BY A.REVIEW_DATE