


SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME > B.DATETIME
ORDER BY A.DATETIME 










# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_INS A
# JOIN ANIMAL_OUTS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE A.DATETIME > B.DATETIME
# ORDER BY A.DATETIME

# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_INS A
# JOIN ANIMAL_OUTS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE A.DATETIME > B.DATETIME
# ORDER BY A.DATETIME

# # SELECT B.ANIMAL_ID, B.NAME
# # FROM ANIMAL_INS A
# #     JOIN ANIMAL_OUTS B
# # ON A.ANIMAL_ID = B.ANIMAL_ID
# # WHERE A.DATETIME > B.DATETIME
# # ORDER BY A.DATETIME

# # -- IN 보다 OUT이 더 빠른 경우..
# # -- SELECT로는 B를 잡고 ON 에는 ID가 같은 경우, WHERE에는 A가 더 늦어서 더 큰 경우
# # -- 마지막에는 A의 시간에 따라 정렬한다.