-- 코드를 작성해주세요

SELECT SUM(A.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_GRADE A
JOIN HR_EMPLOYEES B
ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO
ORDER BY 1 DESC
LIMIT 1












# SELECT SUM(B.SCORE) SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
# FROM HR_EMPLOYEES A JOIN HR_GRADE B
# ON A.EMP_NO = B.EMP_NO
# GROUP BY B.EMP_NO
# ORDER BY 1 DESC
# LIMIT 1;